# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -workspace Example/JSONParserSwift.xcworkspace -scheme JSONParserSwift-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' build-for-testing test | xcpretty
- pod lib lint
